# Generated by Django 2.2 on 2020-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_lang', models.TextField(blank=True, null=True)),
                ('en_lang', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.FloatField()),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
    ]
